### ISSUE TITLE
Does it work with java9?

### ISSUE THREAD

**Issue by ptahchiev** [google/compile-testing#151]
Hey guys,

with java8 my project works fine, but with java9 I get tons of these errors:
```
  /home/petar/.m2/repository/org/springframework/boot/spring-boot-test/2.0.4.BUILD-SNAPSHOT/spring-boot-test-2.0.4.BUILD-SNAPSHOT.jar: Too many open files
No files were generated.

	at com.google.testing.compile.CompilationSubject.succeeded(CompilationSubject.java:79)
	at com.google.testing.compile.JavaSourcesSubject$CompilationClause.compilesWithoutError(JavaSourcesSubject.java:290)
	at com.nemesis.platform.core.mixin.processor.MixInAnnotationProcessorTest.testNameable(MixInAnnotationProcessorTest.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at [[Testing framework: 9 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

[ERROR] testCatalogable(com.nemesis.platform.core.mixin.processor.MixInAnnotationProcessorTest)  Time elapsed: 3.586 s  <<< FAILURE!
java.lang.AssertionError: Compilation produced the following errors:
/home/petar/workspace/nemesis-platform/nemesis-platform-core/target/test-classes/processor/catalog/TestMixInClassesConfig.java:0: error: cannot access com.example.config

  /home/petar/.m2/repository/org/codehaus/janino/janino/3.0.8/janino-3.0.8.jar: Too many open files
/home/petar/workspace/nemesis-platform/nemesis-platform-core/target/test-classes/processor/catalog/TestCatalogableEntityDefinition.java:0: error: cannot access com.nemesis.platform.core.test.definition.catalog

  /home/petar/.m2/repository/org/codehaus/janino/janino/3.0.8/janino-3.0.8.jar: Too many open files
/home/petar/workspace/nemesis-platform/nemesis-platform-core/target/test-classes/processor/catalog/TestExampleEntityDefinition.java:0: error: cannot access com.example.core.definition.catalog

  /home/petar/.m2/repository/org/codehaus/janino/janino/3.0.8/janino-3.0.8.jar: Too many open files
No files were generated.

	at com.google.testing.compile.CompilationSubject.succeeded(CompilationSubject.java:79)
	at com.google.testing.compile.JavaSourcesSubject$CompilationClause.compilesWithoutError(JavaSourcesSubject.java:290)
	at com.nemesis.platform.core.mixin.processor.MixInAnnotationProcessorTest.testCatalogable(MixInAnnotationProcessorTest.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)

```

**Comment by ptahchiev** [comment]
OK, I'm closing this issue - it seems to be a java9 thing. After increasing the limits of my OS it works fine now. Sorry about the noise.
