### ISSUE TITLE
[feature request] support assert generate multi source file.

### ISSUE THREAD

**Issue by vipcxj** [google/compile-testing#212]
My annotation processor generate multi file for a annotationed class. If I use `com.google.testing.compile.CompilationSubject#generatedSourceFile` to test it. It said:
```
expected to generate file: /io/github/vipcxj/beanknife/tests/otherbeans/TestBean1Meta.java
in location              : SOURCE_OUTPUT
it generated:
  /SOURCE_OUTPUT/io/github/vipcxj/beanKnfie/tests/otherbeans/TestBean1Meta.java
  /SOURCE_OUTPUT/io/github/vipcxj/beanknife/tests/beans/TestBean1Meta.java
  /SOURCE_OUTPUT/io/github/vipcxj/beanKnfie/tests/otherbeans/ViewOfTestBean1.java
  /SOURCE_OUTPUT/io/github/vipcxj/beanknife/tests/beans/ViewOfTestBean1.java

	at io.github.vipcxj.beanknife.tests.ViewMetaProcessorTest.testViewMetaCase(ViewMetaProcessorTest.java:50)
	at io.github.vipcxj.beanknife.tests.ViewMetaProcessorTest.testBean1(ViewMetaProcessorTest.java:18)
```
And I can't find a method to support this use case.

**Comment by vipcxj** [comment]
My fault, `beanKnfie` is not equal to `beanknife`
