### ISSUE TITLE
Access to compiler internal APIs will fail starting with JDK 16

### ISSUE THREAD

**Issue by eamonnmcmanus** [google/compile-testing#222]
JDK 16 will [change](https://openjdk.java.net/jeps/396) the default for the `--illegal-access` flag from `permit` to `deny`. This means that, by default, compile-testing tests will fail with messages like this:

```
class com.google.testing.compile.Parser (in unnamed module @0x4114d843) cannot access class
com.sun.tools.javac.api.JavacTool (in module jdk.compiler) because module jdk.compiler does not export
com.sun.tools.javac.api to unnamed module @0x4114d843
```

That can be worked around either by explicitly specifying, on the command line of the JVM running the tests, either `--illegal-access=permit` or `--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED`. We should document that, and perhaps later find a way to make it unnecessary.

**Comment by ZacSweers** [comment]
Just mentioning that the `--illegal-access` flag was removed in JDK 17, so any solution for this would likely need to use `--add-opens`

**Comment by h908714124** [comment]
Users should probably start avoiding methods `containsElementsIn` and `hasSourceEquivalentTo` in `JavaFileObjectSubject`. These use `Parser` internally, which depends on forbidden Sun APIs, and should be deprecated. With some effort, it should be possible to rewrite affected tests to use method `generatedSourceFile` in class `Compilation` instead. See [this commit](https://github.com/jbock-java/jbock/commit/66978d170fce0e5562623bc65dba69c008fd2055) for example.

**Comment by almogtavor** [comment]
@h908714124 is right, but as a workaround:
```java
test {
    jvmArgs "--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED"
    useJUnitPlatform()
}
```
would work

**Comment by mikewacker** [comment]
@almogtavor Here's an updated workaround for Gradle:

```groovy
test {
    useJUnitPlatform()

    // See: https://github.com/google/compile-testing/issues/222
    jvmArgs '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED'
    jvmArgs '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED'
    jvmArgs '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED'
}
```

Notes:

- You only need to use `--add-exports`, `--add-opens` is overkill.
- As of release `0.20`, two additional `--add-exports` are needed. See: cd2c0a8b86f079e68712f07a0e8cfdef1ab28ff4

**Comment by xenoterracide** [comment]
looks like I just hit this

```
    java.lang.IllegalAccessError: class com.google.testing.compile.Parser (in unnamed module @0x15bbf42f) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x15bbf42f
        at com.google.testing.compile.Parser.parse(Parser.java:63)
        at com.google.testing.compile.JavaFileObjectSubject.performTreeDifference(JavaFileObjectSubject.java:173)
        at com.google.testing.compile.JavaFileObjectSubject.hasSourceEquivalentTo(JavaFileObjectSubject.java:126)
        at com.xenoterracide.bygger.ClassAnnotationTest.testImmutable(ClassAnnotationTest.java:53)
```

**Comment by xenoterracide** [comment]
Here's the kotlin dsl (which is now the default) equivalent of the above

```kotlin
tasks.test.configure {
  useJUnitPlatform()

  // See: https://github.com/google/compile-testing/issues/222
  jvmArgs =listOf(
    "--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
    "--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED",
    "--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED"
  )
```

**Comment by ChristophLoy** [comment]
> Here's the kotlin dsl (which is now the default) equivalent of the above
> 
> ```kotlin
> tasks.test.configure {
>   useJUnitPlatform()
> 
>   // See: https://github.com/google/compile-testing/issues/222
>   jvmArgs =listOf(
>     "--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
>     "--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED",
>     "--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED"
>   )
> ```

This is **not** the same! By assigning the jvmArgs via the `=` operator, you remove all existing jvmArgs. The actual equivalent would be:

```kotlin
    jvmArgs("--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED")
    jvmArgs("--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED")
    jvmArgs("--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED")
```

**Comment by cgruber** [comment]
Did this get done? I just ran into this, in 2025, and this issue is still open.
