### ISSUE TITLE
Incompatibility with the last version of truth

### ISSUE THREAD

**Issue by BraisGabin** [google/compile-testing#363]
I'm getting this exception after update the version of truth updates:

```
...
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/MoreCollectors
	at com.google.testing.compile.InMemoryJavaFileManager.findInMemoryInput(InMemoryJavaFileManager.java:134)
	at com.google.testing.compile.InMemoryJavaFileManager.findInMemoryInput(InMemoryJavaFileManager.java:121)
	at com.google.testing.compile.InMemoryJavaFileManager.getJavaFileForInput(InMemoryJavaFileManager.java:112)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.getJavaFileForInput(ClientCodeWrapper.java:287)
	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.getModuleInfoFromLocation(ModuleFinder.java:282)
	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findModuleInfo(ModuleFinder.java:360)
	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findAllModules(ModuleFinder.java:191)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.getUnnamedModuleCompleter(Modules.java:1416)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:462)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:267)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:233)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initModules(JavaCompiler.java:1041)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:939)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
	... 89 more
```

The last version of truth updates guava and I think that is the issue.

Here is the PR that shows this issue: https://github.com/SchwarzIT/dagger-lightsaber/pull/3

**Comment by cpovirk** [comment]
Thanks. This is a general issue with any project that depends on `guava-jre` but also depends on a project that depends on `guava-android` :( The workaround is to [declare a dependency on the newest version of `guava-jre`](https://truth.dev/#:~:text=one%20warning) ([currently `32.1.1-jre`](https://github.com/google/guava/releases)). (And then presumably Renovate will automatically keep you up to date with the latest `guava-jre`, preventing the problem from arising again, at least as long as you bump the Guava version each time before you bump the Truth version.)

We recently [put some magic in place to make _Gradle_ pick the right version automatically](https://github.com/google/guava/releases/tag/v32.1.0), but there's no similar solution for Maven.

It's possible that we can still make things better, either by releasing separate, Guava-style `truth:1.1.6-android` and `truth:1.1.6-jre` "versions" (which would be identical except for their Guava dep) or by making `guava-android` contain APIs like `MoreCollectors`. I'm hoping that we'll at least make some progress on the latter front later this year. You can follow https://github.com/google/guava/issues/6567. Sorry for the ongoing trouble in the meantime.
