### ISSUE TITLE
JDK16+ --add-exports not working as expected

### ISSUE THREAD

**Issue by elkkhan** [google/compile-testing#399]
Hi all,

I'm trying dig into internals of Error Prone using this library - since Error Prone is using JDK internals, I'm passing `--add-exports` for those modules, but this doesn't seem to work as expected.
Same `--add-exports` work when passing them in through Maven.

Example code below:

```java
    final Compiler compiler = Compiler.javac().withOptions(List.of(
            "--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.source.tree=ALL-UNNAMED",
            "-Xplugin:ErrorProne",
            "-XDcompilePolicy=simple"))
        .withClasspath(List.of(new File("target/classes")));
    final Compilation compiled = compiler.compile(JavaFileObjects.forResource("Victim.java"));
```

Stacktrace:

```java
An exception has occurred in the compiler (21.0.1). Please file a bug against the Java compiler via the Java bug reporting page (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.IllegalAccessError: class com.google.errorprone.BaseErrorProneJavaCompiler (in unnamed module @0x1d548a08) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x1d548a08
	at com.google.errorprone.BaseErrorProneJavaCompiler.addTaskListener(BaseErrorProneJavaCompiler.java:92)
	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:34)
	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugin(BasicJavacTask.java:256)
	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:230)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:204)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at com.google.testing.compile.Compiler.compile(Compiler.java:201)
	at com.google.testing.compile.Compiler.compile(Compiler.java:173)
	at org.offen.compiletest.CompilationLab.main(CompilationLab.java:27)
Exception in thread "main" com.google.testing.compile.CompilationFailureException: compilation of [/Users/elkhaneminov/private/errorprone-idea/victim/target/classes/Victim.java] passing options [--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.source.tree=ALL-UNNAMED, -Xplugin:ErrorProne, -XDcompilePolicy=simple] failed, but did not report any error diagnostics or throw any exceptions. This behavior has been observed in older versions of javac, which swallow exceptions and log them on System.err. Check there for more information.
	at com.google.testing.compile.Compiler.compile(Compiler.java:210)
	at com.google.testing.compile.Compiler.compile(Compiler.java:173)
	at org.offen.compiletest.CompilationLab.main(CompilationLab.java:27)
```
Might be worth to note that all the options do get passed into the JavacTask - I debugged the working maven compile with `mvndebug` and the `Options` collection looks exactly the same in the happy path too.

<img width="1315" alt="Screenshot 2024-01-07 at 04 23 04" src="https://github.com/google/compile-testing/assets/32901337/b12845f7-ebe7-4cd4-9bd7-dd8b1e6ea536">

In this particular example I'm using JDK 21, but I've also tried with 17 and no luck.

**Comment by cpovirk** [comment]
My memory on this is fuzzy, but I want to say that you need to pass those as `-J` options (`-J--add-exports=jdk.compiler/...`) and/or that you need to set them on the original test VM rather than trying to pass them to `Compiler.javac().withOptions`, maybe?

I'd probably try the latter, given that it's [what Error Prone does for its `maven-surefire-plugin` run](https://github.com/google/error-prone/blob/654b1d98b76f769dc7576d0999d2d3dcf21c6e90/pom.xml#L237).

**Comment by elkkhan** [comment]
Hi @cpovirk, thanks for the response!
Unfortunately both tips didn't work:
- Passing `-J` type flags to the compiler via Java Compiler API is [not supported](https://github.com/openjdk/jdk/blob/d47393bd8225e818f0f9cd45192a5e656018af11/src/jdk.compiler/share/classes/com/sun/tools/javac/main/Option.java#L1394-L1401) (`J` flag [is not](https://github.com/openjdk/jdk/blob/d47393bd8225e818f0f9cd45192a5e656018af11/src/jdk.compiler/share/classes/com/sun/tools/javac/main/Option.java#L517) in the `BASIC` OptionGroup)

- Passing those options to the JVM also didn't do anything (attaching a screnshot below in case I misunderstood what you meant by that)
<img width="874" alt="Screenshot 2024-01-08 at 20 56 06" src="https://github.com/google/compile-testing/assets/32901337/3d0b03ad-bc5e-4d79-9913-d8002c70e818">

**Comment by elkkhan** [comment]
Hi @cpovirk, thanks for the response!
Unfortunately both tips didn't work:
- Passing `-J` type flags to the compiler via Java Compiler API is [not supported](https://github.com/openjdk/jdk/blob/d47393bd8225e818f0f9cd45192a5e656018af11/src/jdk.compiler/share/classes/com/sun/tools/javac/main/Option.java#L1394-L1401) (`J` flag [is not](https://github.com/openjdk/jdk/blob/d47393bd8225e818f0f9cd45192a5e656018af11/src/jdk.compiler/share/classes/com/sun/tools/javac/main/Option.java#L517) in the `BASIC` OptionGroup)

- Passing those options to the JVM also didn't do anything (attaching a screnshot below in case I misunderstood what you meant by that)
<img width="874" alt="Screenshot 2024-01-08 at 20 56 06" src="https://github.com/google/compile-testing/assets/32901337/3d0b03ad-bc5e-4d79-9913-d8002c70e818">
___________________________________________________________________________________________

**EDIT**: Apologies, I was setting the options on the wrong text field (program arguments). Everything worked once I set them as VM options (Modify Options -> Add VM options).

Thanks alot @cpovirk!

**Comment by cpovirk** [comment]
Great, I'm glad it worked!

I wonder if we should have Compile-Testing produce an error if anyone tries to pass it these flags. The error could advise people what to do instead.

**Comment by elkkhan** [comment]
> Great, I'm glad it worked!
> 
> 
> 
> I wonder if we should have Compile-Testing produce an error if anyone tries to pass it these flags. The error could advise people what to do instead.

that sounds like a nice improvement, i'd like to try to contribute this. will get on it this week

**Comment by elkkhan** [comment]
@cpovirk can you please take a look at the attached PR?
Thanks!
