### ISSUE TITLE
Unknown variable type java.util.Map<java.lang.String,java.lang.Integer> for declared

### ISSUE THREAD

**Issue by vanniktech** [google/compile-testing#78]
I don't know if I am doing something wrong but this seems odd to me.

To reproduce this:

```java
@Test
public void testMap() {
    final JavaFileObject actualSource = JavaFileObjects.forSourceString("test/MapTest", Joiner.on('\n').join(
        "package test;",

        "import nsmodelextractor.Extract;",

        "import java.util.Map;",
        "import java.lang.String;",
        "import java.lang.Integer;",

        "public class MapTest {",
            "@Extract Map<String, Integer> map = null;",
        "}")
    );

    assertAbout(javaSource()).that(actualSource).compilesWithoutError();
}
```

The extract annotations looks like this

```java
@Retention(CLASS)
@Target(FIELD)
public @interface Extract {
    String name() default "";
}
```

I also tried it without any imports. However I keep on getting

> Unknown variable type java.util.Map<java.lang.String,java.lang.Integer> for declared

I'm using `com.google.testing.compile:compile-testing:0.7`

**Comment by vanniktech** [comment]
That errors also exists in `com.google.testing.compile:compile-testing:0.8`

**Comment by eamonnmcmanus** [comment]
I haven't tried this, but could the problem be that you need to make `nsmodelextractor.Extract` available to the compiler, either by including its source or by supplying a `-classpath`?

**Comment by vanniktech** [comment]
No. Since everything works fine when I use primitive types or types like String, Integer, Float etc. As an example, the Java File class below works perfectly fine.

```java
final JavaFileObject actualSource = JavaFileObjects.forSourceString("test/MapTest", Joiner.on('\n').join(
    "package test;",

    "import nsmodelextractor.Extract;",

    "public class MapTest {",
        "@Extract int myInt",
        "@Extract float myFloat",
        "@Extract double myDouble",
        "@Extract Integer myInteger",
        "@Extract Float myFloat",
        "@Extract String myString",
    "}")
);
```

**Comment by eamonnmcmanus** [comment]
I'm not able to reproduce the problem. Can you paste the complete failure output?

**Comment by eamonnmcmanus** [comment]
Also, is this a failure when you are running from within Eclipse, by any chance?

**Comment by vanniktech** [comment]
I'm running Android Studio 1.5 Preview.

![screen shot 2015-10-21 at 9 14 46 am](https://cloud.githubusercontent.com/assets/5759366/10630043/37908c32-77d4-11e5-92a6-7520e0ce7e4f.png)

Failure output:

```
java.lang.AssertionError: Compilation produced the following errors:

test/MapTest.java:3: error: cannot find symbol
import java.lang.Map;
                ^
  symbol:   class Map
  location: package java.lang
test/MapTest.java:4: error: cannot find symbol
public class MapTest{@Extract Map<String, Integer> map;}
                                           ^
  symbol:   class Map
  location: class test.MapTest
error: Unknown type kind ERROR


(No files were generated.)

    at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:27)
    at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:23)
    at com.google.testing.compile.JavaSourcesSubject$CompilationClause.compilesWithoutError(JavaSourcesSubject.java:294)
    at nsmodelextractor.util.JavaFileObjectUtils.assertEquals(JavaFileObjectUtils.java:23)
    at nsmodelextractor.ExtractTest.testExtractMapStringIntegerShouldBeHandledProperly(ExtractTest.java:139)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by eamonnmcmanus** [comment]
That's a different failure from what you said initially, due to using `java.lang.Map` instead of `java.util.Map`.

**Comment by vanniktech** [comment]
That's right. Seems like I mixed it up. Sorry for the confusion.
