### ISSUE TITLE
NPE when generated source is package-info.java

### ISSUE THREAD

**Issue by tsachev** [google/compile-testing#85]
My annotation processor generates `package-info.java` source files.
But when I call generatesSources() NPE is thrown?

```
java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
    at com.google.common.collect.FluentIterable.<init>(FluentIterable.java:82)
    at com.google.common.collect.FluentIterable$1.<init>(FluentIterable.java:91)
    at com.google.common.collect.FluentIterable.from(FluentIterable.java:90)
    at com.google.testing.compile.TypeEnumerator$TypeScanner.visitCompilationUnit(TypeEnumerator.java:103)
    at com.google.testing.compile.TypeEnumerator$TypeScanner.visitCompilationUnit(TypeEnumerator.java:55)
    at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:550)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:77)
    at com.google.testing.compile.TypeEnumerator$TypeScanner.scan(TypeEnumerator.java:59)
    at com.google.testing.compile.TypeEnumerator.getTopLevelTypes(TypeEnumerator.java:49)
    at com.google.testing.compile.JavaSourcesSubject$CompilationClause$1.apply(JavaSourcesSubject.java:178)
    at com.google.testing.compile.JavaSourcesSubject$CompilationClause$1.apply(JavaSourcesSubject.java:176)
    at com.google.common.collect.Maps.toMap(Maps.java:1119)
    at com.google.common.collect.Maps.toMap(Maps.java:1097)
    at com.google.testing.compile.JavaSourcesSubject$CompilationClause.parsesAs(JavaSourcesSubject.java:183)
    at com.google.testing.compile.JavaSourcesSubject.parsesAs(JavaSourcesSubject.java:93)
    at com.google.testing.compile.JavaSourcesSubject$SuccessfulCompilationBuilder.generatesSources(JavaSourcesSubject.java:482)
    at com.nemesis.platform.core.mixin.processor.MixInAnnotationProcessorTest.test(MixInAnnotationProcessorTest.java:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

```

```
assertAbout(javaSources())
                        .that(ImmutableList.of(JavaFileObjects.forResource(Resources.getResource("definition/package-info.java"))))
                        .processedWith(new MixInAnnotationProcessor())
                        .compilesWithoutError().and()
                        .generatesSources(JavaFileObjects.forResource(Resources.getResource("entity/package-info.java")));
```

**Comment by tsachev** [comment]
I found a bug in my annotation processor I was using 
```
processingEnv.getFiler().createResource(StandardLocation.SOURCE_OUTPUT, pkg, fileName)
```
instead of 
```
processingEnv.getFiler().createSourceFile(pkg + "." + fileName.substring(0, fileName.length()- ".java".length()))
```

Now I get 
```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Not supported: InMemoryJavaFileObject{uri=mem:///SOURCE_OUTPUT/com/example/test/definition/package-info.java, kind=SOURCE}

	at com.sun.tools.javac.main.Main.compile(Main.java:559)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.google.testing.compile.Compilation.compile(Compilation.java:77)
	at com.google.testing.compile.JavaSourcesSubject$CompilationClause.compilesWithoutError(JavaSourcesSubject.java:283)
	at com.nemesis.platform.core.mixin.processor.MixInAnnotationProcessorTest.test(MixInAnnotationProcessorTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.IllegalArgumentException: Not supported: InMemoryJavaFileObject{uri=mem:///SOURCE_OUTPUT/com/example/test/definition/package-info.java, kind=SOURCE}
	at com.sun.tools.javac.file.JavacFileManager.isSameFile(JavacFileManager.java:647)
	at javax.tools.ForwardingJavaFileManager.isSameFile(ForwardingJavaFileManager.java:90)
	at com.google.testing.compile.InMemoryJavaFileManager.isSameFile(InMemoryJavaFileManager.java:88)
	at com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.isSameFile(ClientCodeWrapper.java:257)
	at com.sun.tools.javac.comp.Enter.visitTopLevel(Enter.java:310)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
	at com.sun.tools.javac.comp.Enter.classEnter(Enter.java:258)
	at com.sun.tools.javac.comp.Enter.classEnter(Enter.java:272)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:486)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.enterTrees(JavacProcessingEnvironment.java:1015)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:902)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:921)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1187)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 31 more
```

**Comment by tsachev** [comment]
any chance to have support for `pacakge-info.java`?

**Comment by netdpb** [comment]
I have a fix for this code path. But the modern API should work for this use case without NPE:

```java
Compilation compilation = javac().withProcessors(…).compile(sources…);
assertThat(compilation)
    .generatedSourceFile("expected.package-info")
    .hasSourceEquivalentTo(JavaFileObjects.forResource(…));
```
