### ISSUE TITLE
Guava mismatch between compile-testing and tools.jar causes runtmie issues.

### ISSUE THREAD

**Issue by tonycosentini** [google/compile-testing#93]
When I use multiple annotation processors (via the `.processedWith()` API), I get this runtime exception:

```
java.lang.RuntimeException: java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.append(Ljava/lang/Iterable;)Lcom/google/common/collect/FluentIterable;
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.google.testing.compile.Compilation.compile(Compilation.java:76)
	at com.google.testing.compile.JavaSourcesSubject$CompilationClause.successfulCompilationResult(JavaSourcesSubject.java:298)
	at com.google.testing.compile.JavaSourcesSubject$CompilationClause.compilesWithoutError(JavaSourcesSubject.java:288)
```

I think the Java tools jar is also using Guava, but a very old version with different APIs.

**Comment by tonycosentini** [comment]
I'm not sure this is a compile-testing issue - I think it might be related with how I'm using Dagger 2 with compile-testing.

Will reopen if I have more concrete details - sorry for the noise.
